include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    unused_import: warning
    dead_code: warning

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: true
    use_super_parameters: true
    prefer_final_fields: true
